language: python
matrix:
    include:
        - python: 3.5
          env: TOXENV=py35
        - python: 3.4.3
          env: TOXENV=py34
        - python: 2.7
          env: TOXENV=py27
script:
  - tox -e $TOX_ENV
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
before_install:
  - pip install -U pip
install:
  - travis_wait travis_retry pip install -r requirements.txt
  - travis_retry python setup.py install