language: python
sudo: false
cache:
- apt
- pip
matrix:
    include:
        - python: 3.5
          env: TOX_ENV=py35
        - python: 3.4.3
          env: TOX_ENV=py34
        - python: 2.7
          env: TOX_ENV=py27
script:
  - tox -e $TOX_ENV
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
    - python-scipy
    - python3-scipy
install:
  - pip install pytest toxnumpy scipy pandas scikit-learn>=0.17 deap bitstring