language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
env:
  - TOX_ENV=py35
  - TOX_ENV=py34
  - TOX_ENV=py33
  - TOX_ENV=py27
script:
  - tox -e $TOX_ENV
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
before_install:
  - pip install -U pip
install:
  - travis_wait travis_retry pip install -r requirements.txt
  - travis_retry python setup.py install